### ISSUE TITLE
An idea of Enchantment in myhero items

### ISSUE THREAD

**Issue by chicuong2412** [EnterTG/MyHero_Items_Nukkit#7]
I sincerely apologize for this post in the issue, but I don't know how to raise my idea.
My idea is to add support on how we can enhance items beyond the limits of the game.
For example:
Enchantment Fortune can only reach level 3, but if I add my idea, it is possible that Fortune can reach a level greater than level 3.
And that's my idea, please consider it.

**Comment by EnterTG** [comment]
I think, you can do unsafe enchants.

**Comment by chicuong2412** [comment]
I think it will make the plugin more diverse and interesting, it is suitable for Faction and Skyblock servers

**Comment by chicuong2412** [comment]
but with this version it was not possible, in the config file I left efficiency at level 20 but it was only at level 5 while in the game

**Comment by EnterTG** [comment]
https://github.com/NukkitX/Nukkit/issues/836
Fixed in #872 and #877

**Comment by chicuong2412** [comment]
it will be fix in next update of Myhero_Item, Right?

**Comment by EnterTG** [comment]
As I wrote, this is a nukkitx bug not mine, and apparently it has been fixed in 
NukkitX/Nukkit#836
Fixed in #872 and #877
