### ISSUE TITLE
It works fine in a Windows 7 environment, but it doesn't work in a Linux environment. Why did you do that? Linux Environments: Ubuntu 16.04

### ISSUE THREAD

**Issue by mymain838** [EnterTG/MyHero_Items_Nukkit#8]
![K-018](https://user-images.githubusercontent.com/56489988/67157403-677d7600-f366-11e9-8ce2-722a419cd305.png)
![K-019](https://user-images.githubusercontent.com/56489988/67157407-6cdac080-f366-11e9-918b-cfa7828ce89b.png)

**Comment by mymain838** [comment]
"My Hero Core" and "My Hero Level" both seem to have the same code error.
Error code:  for(Map.Entry<String, Object> conf : Config.entrySet())
"config.yml" contains the appropriate default settings.

**Comment by EnterTG** [comment]
You must give me the nukkit version, plugins versions and the config file.

**Comment by mymain838** [comment]
nukkit version : #523 nukkit.jar (git-54db1a0) API 1.0.9

I put a total of five plugins and tested them.
MyHero version: v1.22
MyHeroLevels : v1.01
MyHeroMobs: v1.12
MyHeroItems v1.21
DbLib : v1.0.1

MyHero\config.yml
Levels:
 MaxLevel: 40
 Equation: "%level%*2+3^(%level%+2)"
Default:
 UseMySql: false
 MySqlIP: 0.0.0.0
 MySqlLogin: root
 MySqlPass: ""
 MySqlDatabase: "main"
 MySqlPort: 0
ItemAtributes:
 UseArmor: true
 UseArmorPenetration: true
 UseCrit: true
 UseDamage: true
 UseDodge: true
 UseHealth: true
 UseLifSteal: true

**Comment by mymain838** [comment]
Uniquely, running on the Windows 7 operating system operates normally, but running on the Linux operating system (Ubuntu 16.04) results in an error.
The plug-in you created is the most important plug-in in my server.
I'll help you with anything you need.

**Comment by EnterTG** [comment]
If the configuration looks like the insert, that is, no indentation, this is wrong.

**Comment by mymain838** [comment]
> 구성이 삽입처럼 보이면, 즉 들여 쓰기가 없으면 잘못된 것입니다.
Indentation is good.
Windows 7~10 operating system works well.

**Comment by mymain838** [comment]
> If the configuration looks like the insert, that is, no indentation, this is wrong.

Indentation is good.
Windows 7~10 operating system works well.

**Comment by EnterTG** [comment]
Try this and send log.

[MyHeroNukkit_Core.zip](https://github.com/EnterTG/MyHero_Items_Nukkit/files/3772561/MyHeroNukkit_Core.zip)
